### ISSUE TITLE
site for hosting InteractiveHtmlBom for open hardware projects?

### ISSUE THREAD

**Issue by aewallin** [openscopeproject/InteractiveHtmlBom#65]
Is there a site that is willing to host InteractiveHtmlBom pages for open hardware projects?

Similar to Travis-builds, testing-dashboards etc?
Ideally the BOM-page would autogenerate once you commit to the git-repo of the project.

thanks!

**Comment by damped** [comment]
I have been trying to build BOMs using gitlab's CI/CD build service.
```
image: rjw57/kicad

pages:
        script:
                - ls
                - apt-get update -qq && apt-get install -y git
                - git clone https://github.com/openscopeproject/InteractiveHtmlBom.git
                - mkdir public
                - python2 InteractiveHtmlBom/InteractiveHtmlBom/generate_interactive_bom.py /pcb/pcb.kicad_pcb
                - mv ### /public/###    #will change this to the output file name when it works
                - ls

        artifacts:
                paths:
                        - public
        only:
                - master
```
I'm not an expert on this stuff so I have been getting an error when generate_interactive_bom.py is run.
'Unable to access the X Display, is $DISPLAY set properly?' I'm guessing this is because its running headless?

Do you know how I can run the script without a display?

Thanks for making such an amazing tool!

**Comment by qu1ck** [comment]
You don't need to actually _run_ KiCad, you only need to run a fake X server. Xvfb is one option, package I mentioned is newer replacement for it, I'm not sure if it's available on all systems.

Python 2.7 is fine, actually that is exactly the one you need. Your issue now is that pcbnew module is not installed even though i see apt-get install kicad in your script. 
Do you know what system runs gitlab CI? Which repository did you get kicad from? It's possible that the package you use does not have python scripting enabled.

**Comment by qu1ck** [comment]
Both ubuntu 14 and 16 will work. Official ppa has packages for them https://launchpad.net/~js-reynaud/+archive/ubuntu/kicad-5

Don't use 18 since kicad built for that one doesn't support python scripting at the moment.

**Comment by damped** [comment]
This is what I have so far.
```
image: ubuntu:16.04

pages:
        script:
                - ls
                - apt-get update -qq && apt-get install -y software-properties-common
                - add-apt-repository ppa:js-reynaud/kicad-5
                - apt-get update -qq && apt-get install -y xvfb git kicad

                - Xvfb :0 -screen 0 1024x768x16 &> xvfb.log  &
                - git clone https://github.com/openscopeproject/InteractiveHtmlBom.git
                - mkdir public
                - python2 InteractiveHtmlBom/InteractiveHtmlBom/generate_interactive_bom.py /pcb/pcb.kicad_pcb --dest-dir public

        artifacts:
                paths:
                        - public
        only:
                - master
```
Its been running for 15 minutes getting 3d models but it looks good so far. Is there a base package of kicad that will still meet the requirements of InteractiveHtmlBom?

**Comment by damped** [comment]
It just finished...
We're back to `Unable to access the X Display, is $DISPLAY set properly?`

I'll look at it tomorrow.

**Comment by qu1ck** [comment]
You only need kicad base package, no need to install libraries or 3d models. Probably apt-get pulls it because they are recommended, try `--no-install-recommends` flag.
To debug display issue check `$DISPLAY` and also xvfb.log should tell you if something went wrong.

**Comment by damped** [comment]
The `--no-install-recommends` worked great! Cut the run time down to 2 minutes.

I saved `xvfb.log` and echoed `$DISPLAY` and they are both empty.

I will try `xserver-xorg-video-dummy package` but I think I need to edit some config files.

**Comment by qu1ck** [comment]
It appears that DISPLAY will not be set automatically when xvfb is run, try setting it explicitly in your script
`DISPLAY=:0`
Also take a look at xvfb-run
http://manpages.ubuntu.com/manpages/xenial/man1/xvfb-run.1.html

**Comment by damped** [comment]
It's finally working! 
Looks like we came to the same conclusion with `xvfb-run`. I should have just refreshed the page...
```
.gitlab-ci.yml
--------------

image: ubuntu:16.04
#Will save to https://<usrname>.gitlab.io/<repository>/ibom.html

pages:
        script:
                #PCB path name relitive to the root of the repository
                - PCBPATH="pcb/pcb.kicad_pcb"
                - ls
                - apt-get update -qq && apt-get install -y software-properties-common           #For add-apt-repository
                - add-apt-repository ppa:js-reynaud/kicad-5
                - apt-get update -qq && apt-get install -y --no-install-recommends kicad
                - apt-get install -y xvfb git
                - git clone https://github.com/openscopeproject/InteractiveHtmlBom.git

                - mkdir public
                - CURRENTDIR=$(pwd)
                - xvfb-run --auto-servernum --server-args "-screen 0 1024x768x24" python2 InteractiveHtmlBom/InteractiveHtmlBom/generate_interactive_bom.py --no-browser $PCBPATH --dest-dir $CURRENTDIR/public

        artifacts:
                paths:
                        - public
        only:
                - master
```

This is what it looks like when it's in a gitlab repository: [Denford CNC GRBL Controller](https://gitlab.com/damped/denfordcnc)
It should be similar for github.

Thanks for your help qu1ck! Is there anything you would improve?

**Comment by qu1ck** [comment]
Thanks for sharing final config, I'll put this on wiki for visibility.

Only thing I would do is make sure that if something is broken (either my plugin, which I try to avoid but it happens, or pcb has some unsupported feature etc.) and output is not generated, the script fails and you get some sort of notification to investigate.

Also since your board has nothing of interest on the bottom side you can pass `--layer-view F` to plugin script and by default layout of the bom will be front only.

**Comment by damped** [comment]
I added your argument. There might be a better way to do this other than a variable.
```
.gitlab-ci.yml
--------------
image: ubuntu:16.04
#Will save to https://<usrname>.gitlab.io/<repository>/ibom.html

pages:
        script:
                #PCB path name relitive to the root of the repository
                - PCBPATH="pcb/pcb.kicad_pcb"
                #Arguments to pass to IHB seperated by spaces
                - ARGS="--layer-view F"
                - ls
                - apt-get update -qq && apt-get install -y software-properties-common           #For add-apt-repository
                - add-apt-repository ppa:js-reynaud/kicad-5
                - apt-get update -qq && apt-get install -y --no-install-recommends kicad
                - apt-get install -y xvfb git
                - git clone https://github.com/openscopeproject/InteractiveHtmlBom.git

                - mkdir public
                - CURRENTDIR=$(pwd)
                - xvfb-run --auto-servernum --server-args "-screen 0 1024x768x24" python2 InteractiveHtmlBom/InteractiveHtmlBom/generate_interactive_bom.py --no-browser $ARGS $PCBPATH --dest-dir $CURRENTDIR/public

        artifacts:
                paths:
                        - public
        only:
                - master
```
I played with exporting logs on failure but it seemed harder to find those then just looking at the output from the failed job and for some reason when it didn't fail it didn't give me my artifacts.
```
                paths:
                        - public

                when: on_failure
                paths:
                        - logs
                        - public
```
Awesome that it's making it on the wiki!
